### ISSUE TITLE
Peer Review 1

### ISSUE THREAD

**Issue by absheth** [airavata-courses/Gateway-Falcons#14]
Operating system: MacOS

I faced two issues of the same nature:
1) while running dietCron.py in virtual environment
2) while running fitnessCron.py in virtual environment

Find the breakdown of the issue below:

While creating virtual environment according to wiki, I faced the following issue.
```
149-161-163-151:diet absheth$ python3 -m virtualenv env
/usr/local/opt/python/bin/python3.7: No module named virtualenv
```

When the above command gave error, I tried creating virtual environment as follows:
```
149-161-163-151:diet absheth$ virtualenv testEnv
New python executable in /Users/absheth/Documents/akash/gateway-falcons/diet-service/diet/testEnv/bin/python2.7
Also creating executable in /Users/absheth/Documents/akash/gateway-falcons/diet-service/diet/testEnv/bin/python
Installing setuptools, pip, wheel...
done.
```

As you can see above, the virtual environment is being created with python2.7 (python3 did not work).
I was able to activate the virtual environment as follows:
```
149-161-163-151:diet absheth$ source testEnv/bin/activate
(testEnv) 149-161-163-151:diet absheth$ 
```

Upon getting into virtual environment (python2), I tried to run the both the cron files as below:
```
(testEnv) 149-161-163-151:diet absheth$ python dietCron.py
Traceback (most recent call last):
 File “dietCron.py”, line 1, in <module>
   from crontab import CronTab
ImportError: No module named crontab
```

I even tried to run it with python3 but got an error (though a different one)
```
(testEnv) 149-161-163-151:diet absheth$ python3 dietCron.py 
Traceback (most recent call last):
  File "dietCron.py", line 4, in <module>
    cron = CronTab(user=True)
TypeError: __init__() got an unexpected keyword argument 'user'
```

Upload service, and viewing fitness and diet data worked fine with dummy data (no cronjobs for real time data)

Suggestions:
1) Instead of recommending an IDE to make the configure files, a config file can be created which can be kept at a safe location with proper permissions to be imported into different microservices. Editing a file is lot easier than installing an entire software just to edit config files.

**Comment by Praneta-Paithankar** [comment]
Hello Akash,
Thank you for your feedback. I do have some questions regarding your observations.
1 
```
149-161-163-151:diet absheth$ python3 -m virtualenv env
/usr/local/opt/python/bin/python3.7: No module named virtualenv
```
You were unable to create the virtual environment as virtualenv module is not installed. Thank you for pointing out that I forgot to mention python3 as a language for this project.

2.  We should use the virtual environment ( python3).
Try using 
```
virtualenv --python=/usr/bin/python3.*  name_of_your_virtualenv
```
3.
```(testEnv) 149-161-163-151:diet absheth$ python3 dietCron.py 
Traceback (most recent call last):
  File "dietCron.py", line 4, in <module>
    cron = CronTab(user=True)
TypeError: __init__() got an unexpected keyword argument 'user'
```
This looks like python-crontab package is not installed.  please try running `pip install -r requirements.txt` in a virtual environment. It should resolve your issue. 

Let me know if this fixes your issues.

Thank you,
Praneta

**Comment by absheth** [comment]
2019-02-09 19:31:48  absheth  on  149.160.180.231  ~/course/science-gateway-architecture/peer-review/gateway-falcons/diet-service/diet
$ virtualenv --python=/usr/bin/python3.* env
-bash: virtualenv: command not found

Please update the wiki about how to install virtualenv

**Comment by absheth** [comment]
Also, currently both of the microservices are fetching data every hour which makes review very slow.
For the sake of review, can we change that to 5 mins?

**Comment by Praneta-Paithankar** [comment]
I will update both cron jobs.

**Comment by Praneta-Paithankar** [comment]
@absheth I have updated both cron jobs. Please try to test again.

**Comment by absheth** [comment]
<img width="1680" alt="screen shot 2019-02-10 at 15 38 23" src="https://user-images.githubusercontent.com/14033748/52539258-05399380-2d4a-11e9-913f-383fb4d40ff2.png">


I am not sure if this data is being fetch from the user or is it being populated from dummy data.

**Comment by absheth** [comment]
<img width="922" alt="screen shot 2019-02-10 at 15 49 28" src="https://user-images.githubusercontent.com/14033748/52539379-86ddf100-2d4b-11e9-8711-83e9853b440d.png">


I am getting the above error on the diet page. Please check.

**Comment by tylerthedeveloper** [comment]
@absheth I am unable to reproduce this... have you ran both the micro-services ?

**Comment by tylerthedeveloper** [comment]
> <img alt="screen shot 2019-02-10 at 15 38 23" width="1680" src="https://user-images.githubusercontent.com/14033748/52539258-05399380-2d4a-11e9-913f-383fb4d40ff2.png">
> 
> I am not sure if this data is being fetch from the user or is it being populated from dummy data.

This is from the micro-service and not dummy data

**Comment by tylerthedeveloper** [comment]
> <img alt="screen shot 2019-02-10 at 15 49 28" width="922" src="https://user-images.githubusercontent.com/14033748/52539379-86ddf100-2d4b-11e9-8711-83e9853b440d.png">
> 
> I am getting the above error on the diet page. Please check.

@absheth I am unable to reproduce this... have you ran both the micro-services ?

**Comment by absheth** [comment]
> > <img alt="screen shot 2019-02-10 at 15 38 23" width="1680" src="https://user-images.githubusercontent.com/14033748/52539258-05399380-2d4a-11e9-913f-383fb4d40ff2.png">
> > I am not sure if this data is being fetch from the user or is it being populated from dummy data.
> 
> @absheth
> This is from the micro-service and not dummy data

It seemed like dummy data but @Praneta-Paithankar fixed it and it is now working.

**Comment by absheth** [comment]
> > <img alt="screen shot 2019-02-10 at 15 49 28" width="922" src="https://user-images.githubusercontent.com/14033748/52539379-86ddf100-2d4b-11e9-8711-83e9853b440d.png">
> > I am getting the above error on the diet page. Please check.
> 
> @absheth I am unable to reproduce this... have you ran both the micro-services ?

Yes. Both of my microservices were up and running but I was still getting this error. 
It seems fixed now.

**Comment by tylerthedeveloper** [comment]
It is inductive, if one data row works, all will work, so if both servers are (were) up and running, one row would not cause this where the other rows would not; if one works, they all will work

**Comment by absheth** [comment]
Actually, it wasn't working even when both the services were up and running but Praneta fixed something at her end and it started working.
