### ISSUE TITLE
npm was not running on VS code bash

### ISSUE THREAD

**Issue by arswaroop** [airavata-courses/Gateway-Falcons#17]
It was recommended to use VS Code bash for commands but on my computer npm was not running on my bash but it works well on cmd/PS. It would be great if steps are provided for npm to work on bash.

**Comment by tylerthedeveloper** [comment]
NPM not working in vs code (bash) is not a side effect of our installation, that is specific to the node version and npm installation on your computer, please re-open if there is confusion
