### ISSUE TITLE
Update wiki with proper requirements and their installation process

### ISSUE THREAD

**Issue by absheth** [airavata-courses/Gateway-Falcons#21]
I am testing on an operating system with a proper user interface but most of the production servers are generally accessed only via terminal or some kind of command line interface.

Installing VS code will definitely install all the required libraries but when deploying on servers, all the libraries may not be available.

I faced an issue where I did not have Java installed or maven installed and I could not find installation instructions on the wiki page.

Please update the wiki with all the requirements and their dependencies, and how to install them.

**Comment by tylerthedeveloper** [comment]
- Your first remark doesn't seem to be a question, but if so, please let us know how we can help

- VS Code is not used as a "global installation problem solver" and is not a dependency of the project. but rather a suggestion that has had success

- The wiki has been updated and links are provided with installation instructions for java. Please test and verify

**Comment by absheth** [comment]
My first comment was not a question. It is an example of why recommending some IDE for deployment is not ideal.
