### ISSUE TITLE
Upload image doesnt show any message. 

### ISSUE THREAD

**Issue by arswaroop** [airavata-courses/Gateway-Falcons#22]

**Comment by arswaroop** [comment]
1. Need to refresh page manually to check if upload succeeded.
2. Or do something else button doesn't do anything

**Comment by arswaroop** [comment]
3. Not sure how to upload fitness and diet data.

**Comment by tylerthedeveloper** [comment]
1. thanks for pointing that out, will handle reload and re-fetch after success 
2. That was just a place holder, will remove
3. You do not upload fitness or diet data, that is from cron jobs, the front end of the site is read only in those aspects

**Comment by arswaroop** [comment]
Thanks for 1 and 2.
I guess i will have to wait for cron jobs start errors to be fixed. 
Will keep this issue open until then since there's no separate ticket for cron errors.

**Comment by arswaroop** [comment]
1 and 2 are still not handled and also theres no validation of type of file getting uploaded. 
So reopening the ticket. Let me know the update

**Comment by absheth** [comment]
Even I noticed this but as this issue is already raised, I did not raise it again.

**Comment by tylerthedeveloper** [comment]
I am closing this as both have been address and media is an admin / privileged user function and a user will not see it and thus it will be removed from the unauthenticated current site. 

Please pull and verify with [this commit](https://github.com/airavata-courses/Gateway-Falcons/commit/dc1cd13f97e3fa9a304ab3eebe100f6326f71ca2)
