### ISSUE TITLE
Peer Review Milestone 1

### ISSUE THREAD

**Issue by gattur** [airavata-courses/Gateway-Falcons#23]
Hello Team,

User Interface was good and team provided great support in helping solve the issues when i was stuck, especially @Praneta-Paithankar . 

A doubt and a point to provide feedback.

1. Error handling could be provided, to check for successful completion. Instead of hard coding Success.
2. In the napkin diagram i could see two micro services for uploading and fetching media from the same DB. Could i know the reason for two micro services.

Thanks,
Gattu

**Comment by Chirag-Galani** [comment]
Hey @gattur,
@tylerthedeveloper  would address the first issue
For the second point, we initially wanted to create the microservices in 2 languages to satisfy the 3 languages constraint but later realized it's not worth the hassle and switched our cloud provider to Cloudinary which has robust API support.

**Comment by tylerthedeveloper** [comment]
@gattur I would love to help, can you provide some specific examples?

**Comment by gattur** [comment]
@tylerthedeveloper 

GreetingController.java
return "Upload Successful "+data + "\n" + file.getOriginalFilename() + "\n" + file.getSize();

**Comment by Chirag-Galani** [comment]
@gattur If there was an error during the upload process Java Spring automatically sends an error request 500 error indicating error occurred. Also, the spring API is going to support adding a caption and more context related information for images so the API will undergo the re-writing process to support our client's requests.

**Comment by gattur** [comment]
try {
            Map uploadResult = cloudinary.uploader().upload(file.getBytes(), params2);
            System.out.println(uploadResult);
        } catch (IOException e) {
            e.printStackTrace();
        }

        ResponseEntity res = new ResponseEntity<>(HttpStatus.OK);
        HttpHeaders headers = new HttpHeaders();
        headers.add(HttpHeaders.CONTENT_TYPE, "application/json; charset=UTF-8");

//        ResponseEntity.ok()
//                .headers(headers)
//                .body("Upload successfull. Please visit http://localhost:3000");
//        return
        return "Upload Successful "+data + "\n" + file.getOriginalFilename() + "\n" + file.getSize();
    }

Here when an error is thrown, it is caught and printed in the stack trace and continuous the normal execution and returns success.

In the UI, checking if there is a response and continuing execution as a success.

post('http://localhost:8081/upload', formData, config)
            .then((res) => {
                alert("Success");
                this.fetchImages();
            })
            .catch((err) => console.log(err));
 
Please correct me if am wrong.

**Comment by Chirag-Galani** [comment]
I am sorry about that part. I'll fix it. Thanks for informing.

**Comment by Chirag-Galani** [comment]
I have fixed that issue. Please let me know if you face any other issues.
