### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/Gateway-Falcons#35]
Hey team,

I just started with the code review. Will update my progress/issues here.

Thanks,
Nawaz

**Comment by nawazkh** [comment]
Hello Team,

I am stuck at cloning the project. Can you please mention more about _the config file received over email_?  
And, also update the project steps so that It can be run directly from the terminal and doesn't need to be imported in VSCode or other editors.

Please get back to this issue soon.

Thanks, 
Nawaz

**Comment by Chirag-Galani** [comment]
Hi Nawaz,

The config files and Java credentials have been shared on slack.
Also, the project can now run directly using terminal

Best,
Chirag

**Comment by tylerthedeveloper** [comment]
As you can see above
1. Config file: yes, per request it will be distributed... 
2. VS Code is merely a successful suggestion

**Comment by nawazkh** [comment]
Hey Chirag, 

I can understand why this is being sent over email/message.
But since I do not have the editor, can you mention the exact location of the class file I have to change? I can replace it through terminal.

**Comment by tylerthedeveloper** [comment]
There is no change, 
1. the .env file goes into the root and the other files go in a config folder at root level

**Comment by Chirag-Galani** [comment]
Hi Nawaz,
As mentioned on the wiki:
Open java-spring-microservice>src>main>java>hello>GreetingController.java and replace the lines 22, 23 & 24 with credentials received on slack

**Comment by nawazkh** [comment]
Quick question: 
The zip file creates a "config" folder with required json files. 
1) Are we supposed to put the "files" in the back-end/server folder or put the "config" folder with the json files in the back-end/server folder?
2) Is this the same config file to be put in back-end/server-data-ms?

**Comment by Chirag-Galani** [comment]
The config folder needs to be placed in the back-end/server and back-end/server-data-ms.
Please extract the zip there as it also contains a .env hidden file which is not visible to the file viewer

**Comment by nawazkh** [comment]
Great work Team! 

A lot of effort has been put in getting the services right, and it shows! I love your project! 

To provide a summary:
1. Nice work on the UI.
2. run time logs are working good.
3. I saw 2 test cases running as well on the building the java micro service. The more the better during Continuous integration.

Suggestions:
1. It appears to me that the website mostly consists of user upload and user view. Are you also maintaining user profile in a user management service where a user is able to login and save his details ?

Thanks, 
Nawaz

**Comment by Chirag-Galani** [comment]
Hi Nawaz,
We do not plan to add user management soon because the main goal is 1 user can share his bike ride progress with viewers (who doesn't need be logged in to the system). The biker is like an admin account sharing his updates on the go. We are still working on some new and exciting features for the next milestone

**Comment by nawazkh** [comment]
Sou

> Hi Nawaz,
> Thank you for your feedback.
> 
> We do not plan to add user management soon because the main goal is 1 person can share his bike ride progress with viewers (who doesn't need to be logged in to the system). The biker is like an admin account sharing his updates on the go.
> 
> We are still working on some new and exciting features for the next milestone

Sounds good to me! 

However, I would still insist on maintaining a user profile or a stateless login service. This will be a key learning experience when you shift to Kubernetes.

Final thoughts before we close this communication.
1. Please briefly update on the service provided by each micro service and the language it has been developed in.

Keep up the good work!
