### ISSUE TITLE
[WIKI] Update wiki for peer review 2

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/Gateway-Falcons#40]
Update the wiki with latest deployment steps and comment here when its ready.

**Comment by Chirag-Galani** [comment]
Hey,
Our Jenkins server stopped responding last night. We have raised an XSEDE ticket. But, haven't got any response yet. We are setting up the server and will let you know once we are done.

**Comment by Chirag-Galani** [comment]
Hey,
We have updated the wiki page with the steps.
https://github.com/airavata-courses/Gateway-Falcons/wiki/Milestone-2
I have also emailed you the credentials required for Jenkins testing.

**Comment by KalaRaja** [comment]
Please mention what feature work and what do not, because from what i see on the front end, many buttons don't do anything

**Comment by tylerthedeveloper** [comment]
@KalaRaja thanks for the suggestion
- diet data table at bottom is live
- media will be done later today
- fitness will be worked on later today
- /landing has a live counter to the start date
- /about has some information

more updates coming later!

**Comment by tylerthedeveloper** [comment]
please see update to main wiki, bottom of page @KalaRaja
