### ISSUE TITLE
[Service Discovery] Zookeeper API should be a cluster.

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/Gateway-Falcons#51]
1. It would be nice to have an ensemble of Zookeeper servers instead of single zookeeper.
2. The service discovery Rest service defeats the purpose of implementing zookeeper since it is a single endpoint. If it fails, the whole system fails.

There are 3rd party libraries which do service discovery like [Kubernetes](https://kubernetes.io/). If you want do it manually, The clients (microservices) should watch for zookeeper events, and connect to alternate replicas if a node on a path fails.

I changed the service discovery endpoint, simulating server crash and the front end failed.
![screenshot-20190303100233-553x18](https://user-images.githubusercontent.com/42894144/53697104-c4a6c600-3d9b-11e9-88b9-9565151e3959.png)

**Comment by Praneta-Paithankar** [comment]
@KalaRaja 
Thank you for your suggestions. I agree that zookeeper in quorum mode is better than the standalone mode. We are planning to use zookeeper in quorum mode in the next milestone.   
Zookeeper Service takes a few minutes to build.  It's working now.
<img width="954" alt="screen shot 2019-03-03 at 10 11 19 am" src="https://user-images.githubusercontent.com/24793322/53700866-dbadde00-3dc4-11e9-8f1c-68224e046586.png">

**Comment by KalaRaja** [comment]
@Praneta-Paithankar 

I am talking about making the zookeeper service discovery rest API as a cluster too. IF your service descovery REST API crashes, your entire system will crash.

I agree that this cannot be fixed in milestone 2, please keep that as a task for next milestone. [closing]
