### ISSUE TITLE
[JENKINS] suggestion - simplification

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/Gateway-Falcons#52]
There is no need to setup multiple pipeline just for building the services, you can configure individual jobs for building your microservices + front end.

There could be only one pipeline that strings together these jobs an deploy them over production/development/test machines.

you can chain jobs as well if one microservice needs to be built before others. The job build script would then become simple, and there would be minimal groovy pipeline scripts.

Also, instead of SSH to different machines in the pipeline script, you can setup Master slave configuration in  Jenkins, so master can build on slaves with no cumbersome ssh scripting.

**Comment by Chirag-Galani** [comment]
Thanks for the suggestion. 

We talked to the one of the AI of the course and he recommended using individual pipelines for all the branches and a common pipeline (deploy_application) to build them all.

We will definitely look into the Master-Slave Build concept to build the project in the next milestone.
