### ISSUE TITLE
[JENKINS] jenkins does not report build status to GIT

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/Gateway-Falcons#53]
If build fails, the jenkins should push a build fail message to the GIT UI.

there can be two ways of doing this.

1. For CI, every pull request triggers a jenkins pipeline/job, the jenkins builds the pull request and reports the status back to GIT open pull request UI. See the image below
![screenshot-20190303102001-967x557](https://user-images.githubusercontent.com/42894144/53697276-f587fa80-3d9d-11e9-8952-647b474cdf12.png)
> imagine 'Jenkins CI' instead of travis

After the status becomes 'Build passed' then pull request is merged, this serves the purpose of **Continuous integration**

2. Your Jenkins does continuous deployment instead of continuous integration, so for this scenario, the jenkins should have a mechanism of telling the developers that their push passed the build either via email or via using a markdown pill [check this out ](https://wiki.jenkins.io/display/JENKINS/Embeddable+Build+Status+Plugin)

**Comment by Chirag-Galani** [comment]
Hey,
I have updated the readme of all the Jenkins connected branches with markdown pill.
Thanks for sharing that. Also, pull request CI doesn't work perfectly with our current setup on non-SCM Jenkins pipeline script. We will perform pipeline script with freestyle projects and add support for that in the next milestone.
