### ISSUE TITLE
[REACT UI] a lot of console errors

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/Gateway-Falcons#54]

**Comment by tylerthedeveloper** [comment]
Can you be a little more specific? Which pages? 

We have strict linting on so there are many warnings.

Also please note on page reliant on backend service could throw errors if you're not running the respective server.

**Comment by KalaRaja** [comment]
Console errors (All microservices are up, tested using the test urls given)
1.  Live > location
![location](https://user-images.githubusercontent.com/42894144/53698578-8ebe0d80-3dac-11e9-8268-38a2f0ad159a.png)
2.  UI elements > general elements 
![general_elements](https://user-images.githubusercontent.com/42894144/53698591-c0cf6f80-3dac-11e9-8c1f-19c2d0970197.png)
3. Data > diet
![diet](https://user-images.githubusercontent.com/42894144/53698596-e52b4c00-3dac-11e9-8b2f-a5970c050513.png)
4. Data > fitness
![fitness](https://user-images.githubusercontent.com/42894144/53698601-ee1c1d80-3dac-11e9-8e24-61d3651eab9d.png)
5. Data > media
![media](https://user-images.githubusercontent.com/42894144/53698614-2f143200-3dad-11e9-8934-fbd5be3e0789.png)
6. on resizing window
![resize](https://user-images.githubusercontent.com/42894144/53698624-55d26880-3dad-11e9-9056-3b56b7915f92.png)

**Comment by tylerthedeveloper** [comment]
Hello @KalaRaja 

Please review only the **commentary** from this pull request to address the above:

https://github.com/airavata-courses/Gateway-Falcons/pull/56

Then please pull latest changes here to commit (this had a patch on the above commit): 
https://github.com/airavata-courses/Gateway-Falcons/commit/5f72bb5fd411dd33452bd1a2430a382f647b13aa

**Comment by KalaRaja** [comment]
so the branch that is being built by Jenkins is behind latest commit?

**Comment by KalaRaja** [comment]
if the errors are left deliberately for missing features that's okay. My suggestion is to use annotations for that, it's upto you. [closing]
