### ISSUE TITLE
[PR-SUMMARY] summary of my review

### ISSUE THREAD

**Issue by KalaRaja** [airavata-courses/Gateway-Falcons#55]
1. UI looks really good.
2. I didn't have any issues with microservices, all services are up.
3. Zookeeper should be an ensemble instead of standalone. (what if leader dies).
4. Service discovery should be fault tolerant too.
5. Jenkins job is well done, if you want you can simplify it even further.
6. You can implement CI push messages(for pull requests) in jenkins.
7. Very nice to have features would be a pill that shows code coverage, build status (for deployment), documentation coverage and pills to show deployed microservices url and front end. [check this out](https://shields.io/).

**Comment by tylerthedeveloper** [comment]
@Chirag-Galani let's get this jenkins build status that @KalaRaja provided us with the link above, thanks for all the feedback and suggestions!
