### ISSUE TITLE
Peer review 2 

### ISSUE THREAD

**Issue by shubham1812** [airavata-courses/Gateway-Falcons#57]
The backend services and pipeline work well. The build was deployed properly. All services are working.
Areas where you can improve:
It's hard to understand what exactly the UI is showing.
The user has logged in automatically. Don't know if login is a dummy or there is some bug.
Many things are shown, but hard to understand which part is doing what. I am not sure if it is a interacting website or not

**Comment by Chirag-Galani** [comment]
We are still working on the user management part as our application is supposed to be available to the users without logging in or signing up.
Also, the UI components are a little messy cause we just revamped the whole UI and need to fix some components. We will fix that by the next milestone as various features are still being built.
