### ISSUE TITLE
Fitness service Error

### ISSUE THREAD

**Issue by alakhsingh** [airavata-courses/Gateway-Falcons#86]
Hi Team,
As mentioned in the wiki, I tried accessing the URL and it displayed 
'Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.'

Thanks,
Alakh

**Comment by alakhsingh** [comment]
The diet service also displays the same error message.

**Comment by Praneta-Paithankar** [comment]
Both services are working now. Thank you for your feedback
