### ISSUE TITLE
OpenID unable to login

### ISSUE THREAD

**Issue by morparia-p** [airavata-courses/Gateway-Falcons#89]
Hi Team,

I was unable to log in using my Gmail account. Can you take a look into it?
<img width="1440" alt="Screen Shot 2019-04-25 at 10 07 53 PM" src="https://user-images.githubusercontent.com/33207301/56778927-b88d2280-67a6-11e9-988c-3ce591eaa741.png">

**Comment by Praneta-Paithankar** [comment]
@morparia-p Could you tell me how you logged in? Login service is working for me
<img width="1440" alt="Screen Shot 2019-04-28 at 11 23 26 AM" src="https://user-images.githubusercontent.com/24793322/56866539-51d75700-69a8-11e9-9d59-009f38312b17.png">
.

**Comment by morparia-p** [comment]
I used the login in hamburger.
<img width="1440" alt="Screen Shot 2019-04-28 at 9 23 47 PM" src="https://user-images.githubusercontent.com/33207301/56872898-1bc3c280-69fc-11e9-9cea-4c4f48ed6d0b.png">
Got a blank screen after logging in.

**Comment by morparia-p** [comment]
Worked for me on the following server:
http://149.165.168.185/dashboards/home
but did not on 
 http://149.165.170.43
Closing this issue.
