### ISSUE TITLE
haproxy configured only for UI

### ISSUE THREAD

**Issue by AdithyaHS** [airavata-courses/Gateway-Falcons#92]
Hi team,

Excellent work with the project. I noticed on your haproxy config that you have a proxy set up for 2 UI services and I was wondering what would happen if in one of the clusters all the services goes down except for UI ? would you still route the requests to this UI service? if so can it handle it since the other services in its cluster are down ?

**Comment by Chirag-Galani** [comment]
Hey,
WE've used an nginx reverse proxy for mapping those requests internally from frontend to backend and other microservices. We never use a hardcoded IP address to redirect the user as we have 2 HAProxy instances (IU & TACC) and possibly many in the future as we scale. So, we cannot add multiple HA proxy URLs while services talk to each other

**Comment by AdithyaHS** [comment]
Hello Chirag,

From your comment, I understand that nginx proxy maps the requests through localhost which is great however my question is when one of your services goes down in one cluster does the traffic redirect to another cluster if the service going down is not your UI?

**Comment by Chirag-Galani** [comment]
No. We restrict it to a single cluster as there are multiple replicas of every microservice. In case the cluster goes down, it will be handled by HAProxy re-routing to the new cluster's master IP.

**Comment by AdithyaHS** [comment]
Thanks for the info. I will be closing this issue.
